#!/bin/sh

print_help() {
  echo "* start - initialize project"
  echo "* down - stop and remove project"
  echo "* tests - run phpunit tests"
}

compose_start() {
  docker-compose up --build -d
  docker-compose exec app chown -R owner:owner .
  docker-compose exec -u owner app composer install
}

compose_down() {
  docker-compose down
}

compose_tests() {
  docker-compose exec -u owner app php vendor/bin/phpunit
}

case $1 in
start)
  compose_start
  ;;
down)
  compose_down
  ;;
tests)
  compose_tests
  ;;
*)
  print_help
  ;;
esac
